// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: src/proto/network.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerInfo contains information about a peer
type PeerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                          // Unique node identifier
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                      // host:port format
	ConnectedSince int64                  `protobuf:"varint,3,opt,name=connected_since,json=connectedSince,proto3" json:"connected_since,omitempty"` // Unix timestamp when connected
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_src_proto_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerInfo) GetConnectedSince() int64 {
	if x != nil {
		return x.ConnectedSince
	}
	return 0
}

// HandshakeRequest is sent to initiate connection
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Requesting node's ID
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`             // Requesting node's public address
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`        // Request timestamp
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`             // Protocol version
	Nonce         []byte                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`                 // Random nonce for challenge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_src_proto_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HandshakeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HandshakeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HandshakeRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HandshakeRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// HandshakeResponse is returned after successful handshake
type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                               // Whether connection was accepted
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                      // Responding node's ID
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                                      // Access token for authenticated calls
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                    // Rejection reason if not accepted
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // Response timestamp
	NonceResponse []byte                 `protobuf:"bytes,6,opt,name=nonce_response,json=nonceResponse,proto3" json:"nonce_response,omitempty"` // Response to nonce challenge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_src_proto_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HandshakeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HandshakeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HandshakeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HandshakeResponse) GetNonceResponse() []byte {
	if x != nil {
		return x.NonceResponse
	}
	return nil
}

// GetPeersRequest asks for connected peers
type GetPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                        // Auth token
	MaxPeers      int32                  `protobuf:"varint,2,opt,name=max_peers,json=maxPeers,proto3" json:"max_peers,omitempty"` // Max peers to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_src_proto_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeersRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetPeersRequest) GetMaxPeers() int32 {
	if x != nil {
		return x.MaxPeers
	}
	return 0
}

// GetPeersResponse returns list of known peers
type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_src_proto_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{4}
}

func (x *GetPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

// PingRequest for keepalive
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_src_proto_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{5}
}

func (x *PingRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PingResponse for keepalive
type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_src_proto_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{6}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// DisconnectRequest to gracefully disconnect
type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_src_proto_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{7}
}

func (x *DisconnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DisconnectResponse acknowledges disconnect
type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_src_proto_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{8}
}

func (x *DisconnectResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// AuthenticatedRequest wraps any authenticated request
type AuthenticatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticatedRequest) Reset() {
	*x = AuthenticatedRequest{}
	mi := &file_src_proto_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatedRequest) ProtoMessage() {}

func (x *AuthenticatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatedRequest.ProtoReflect.Descriptor instead.
func (*AuthenticatedRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{9}
}

func (x *AuthenticatedRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticatedRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthenticatedRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthenticatedRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthenticatedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// AuthenticatedResponse wraps any authenticated response
type AuthenticatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticatedResponse) Reset() {
	*x = AuthenticatedResponse{}
	mi := &file_src_proto_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatedResponse) ProtoMessage() {}

func (x *AuthenticatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatedResponse.ProtoReflect.Descriptor instead.
func (*AuthenticatedResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{10}
}

func (x *AuthenticatedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticatedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthenticatedResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthenticatedResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Block represents a blockchain block
type Block struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Number         uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	PreviousHash   []byte                 `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MinerAddress   []byte                 `protobuf:"bytes,4,opt,name=miner_address,json=minerAddress,proto3" json:"miner_address,omitempty"`
	TxRoot         []byte                 `protobuf:"bytes,5,opt,name=tx_root,json=txRoot,proto3" json:"tx_root,omitempty"`
	StateRoot      []byte                 `protobuf:"bytes,6,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	CheckpointCid  string                 `protobuf:"bytes,7,opt,name=checkpoint_cid,json=checkpointCid,proto3" json:"checkpoint_cid,omitempty"`
	CheckpointHash []byte                 `protobuf:"bytes,8,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"`
	Transactions   []*Transaction         `protobuf:"bytes,9,rep,name=transactions,proto3" json:"transactions,omitempty"`
	MinerSig       []byte                 `protobuf:"bytes,10,opt,name=miner_sig,json=minerSig,proto3" json:"miner_sig,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_src_proto_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{11}
}

func (x *Block) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Block) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetMinerAddress() []byte {
	if x != nil {
		return x.MinerAddress
	}
	return nil
}

func (x *Block) GetTxRoot() []byte {
	if x != nil {
		return x.TxRoot
	}
	return nil
}

func (x *Block) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *Block) GetCheckpointCid() string {
	if x != nil {
		return x.CheckpointCid
	}
	return ""
}

func (x *Block) GetCheckpointHash() []byte {
	if x != nil {
		return x.CheckpointHash
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetMinerSig() []byte {
	if x != nil {
		return x.MinerSig
	}
	return nil
}

// Transaction represents a blockchain transaction (stateless and self-contained)
// Can be validated in isolation without external state access.
// Two hashes exist:
// - ProposalHash: Implicit hash of the user proposal (can be computed from fields)
// - ID: Hash of the complete transaction including validator's execution evidence
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User Proposal (signed by user before sending to validator)
	TxType     uint32 `protobuf:"varint,2,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"` // Transaction type (0 = transfer, 1 = contract call, etc)
	Validator  []byte `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator,omitempty"`          // Validator chosen to process this transaction
	From       []byte `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To         []byte `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Value      []byte `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Nonce      []byte `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`                              // Replay protection - unique per (From, Nonce) pair
	BlockLimit uint64 `protobuf:"varint,8,opt,name=block_limit,json=blockLimit,proto3" json:"block_limit,omitempty"` // Transaction expires after this block (0 = no limit)
	Data       []byte `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	UserSig    []byte `protobuf:"bytes,10,opt,name=user_sig,json=userSig,proto3" json:"user_sig,omitempty"` // User signature (authorizes the proposal)
	// Execution Evidence (filled by Validator after execution)
	SequenceId    uint64            `protobuf:"varint,11,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	ReadSet       map[string][]byte `protobuf:"bytes,12,rep,name=read_set,json=readSet,proto3" json:"read_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`    // Dependencies: keys AND values read
	WriteSet      map[string][]byte `protobuf:"bytes,13,rep,name=write_set,json=writeSet,proto3" json:"write_set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // State changes (key -> new value)
	ValidatorSig  []byte            `protobuf:"bytes,14,opt,name=validator_sig,json=validatorSig,proto3" json:"validator_sig,omitempty"`                                                               // Validator signature (confirms execution)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_src_proto_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{12}
}

func (x *Transaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transaction) GetTxType() uint32 {
	if x != nil {
		return x.TxType
	}
	return 0
}

func (x *Transaction) GetValidator() []byte {
	if x != nil {
		return x.Validator
	}
	return nil
}

func (x *Transaction) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Transaction) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transaction) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Transaction) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Transaction) GetBlockLimit() uint64 {
	if x != nil {
		return x.BlockLimit
	}
	return 0
}

func (x *Transaction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Transaction) GetUserSig() []byte {
	if x != nil {
		return x.UserSig
	}
	return nil
}

func (x *Transaction) GetSequenceId() uint64 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *Transaction) GetReadSet() map[string][]byte {
	if x != nil {
		return x.ReadSet
	}
	return nil
}

func (x *Transaction) GetWriteSet() map[string][]byte {
	if x != nil {
		return x.WriteSet
	}
	return nil
}

func (x *Transaction) GetValidatorSig() []byte {
	if x != nil {
		return x.ValidatorSig
	}
	return nil
}

// BroadcastBlockRequest broadcasts a new block
type BroadcastBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Block         *Block                 `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastBlockRequest) Reset() {
	*x = BroadcastBlockRequest{}
	mi := &file_src_proto_network_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastBlockRequest) ProtoMessage() {}

func (x *BroadcastBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastBlockRequest.ProtoReflect.Descriptor instead.
func (*BroadcastBlockRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{13}
}

func (x *BroadcastBlockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BroadcastBlockRequest) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// BroadcastBlockResponse acknowledges block receipt
type BroadcastBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastBlockResponse) Reset() {
	*x = BroadcastBlockResponse{}
	mi := &file_src_proto_network_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastBlockResponse) ProtoMessage() {}

func (x *BroadcastBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastBlockResponse.ProtoReflect.Descriptor instead.
func (*BroadcastBlockResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{14}
}

func (x *BroadcastBlockResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BroadcastBlockResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GetBlockRequest requests a specific block
type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Number        uint64                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"` // Block number (if hash is empty)
	Hash          []byte                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`      // Block hash (if number is 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_src_proto_network_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{15}
}

func (x *GetBlockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetBlockRequest) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GetBlockRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// GetBlockResponse returns the requested block
type GetBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Block         *Block                 `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_src_proto_network_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{16}
}

func (x *GetBlockResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

// GetBlocksRequest requests a range of blocks
type GetBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	FromNumber    uint64                 `protobuf:"varint,2,opt,name=from_number,json=fromNumber,proto3" json:"from_number,omitempty"`
	ToNumber      uint64                 `protobuf:"varint,3,opt,name=to_number,json=toNumber,proto3" json:"to_number,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksRequest) Reset() {
	*x = GetBlocksRequest{}
	mi := &file_src_proto_network_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksRequest) ProtoMessage() {}

func (x *GetBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{17}
}

func (x *GetBlocksRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetBlocksRequest) GetFromNumber() uint64 {
	if x != nil {
		return x.FromNumber
	}
	return 0
}

func (x *GetBlocksRequest) GetToNumber() uint64 {
	if x != nil {
		return x.ToNumber
	}
	return 0
}

func (x *GetBlocksRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetBlocksResponse returns multiple blocks
type GetBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksResponse) Reset() {
	*x = GetBlocksResponse{}
	mi := &file_src_proto_network_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksResponse) ProtoMessage() {}

func (x *GetBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{18}
}

func (x *GetBlocksResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// GetLatestBlockRequest requests the latest block
type GetLatestBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestBlockRequest) Reset() {
	*x = GetLatestBlockRequest{}
	mi := &file_src_proto_network_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestBlockRequest) ProtoMessage() {}

func (x *GetLatestBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestBlockRequest.ProtoReflect.Descriptor instead.
func (*GetLatestBlockRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{19}
}

func (x *GetLatestBlockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// GetLatestBlockResponse returns the latest block info
type GetLatestBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint64                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestBlockResponse) Reset() {
	*x = GetLatestBlockResponse{}
	mi := &file_src_proto_network_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestBlockResponse) ProtoMessage() {}

func (x *GetLatestBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestBlockResponse.ProtoReflect.Descriptor instead.
func (*GetLatestBlockResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{20}
}

func (x *GetLatestBlockResponse) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GetLatestBlockResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// BroadcastTransactionRequest broadcasts a new transaction
type BroadcastTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastTransactionRequest) Reset() {
	*x = BroadcastTransactionRequest{}
	mi := &file_src_proto_network_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastTransactionRequest) ProtoMessage() {}

func (x *BroadcastTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastTransactionRequest.ProtoReflect.Descriptor instead.
func (*BroadcastTransactionRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{21}
}

func (x *BroadcastTransactionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BroadcastTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// BroadcastTransactionResponse acknowledges transaction receipt
type BroadcastTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	TxId          string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastTransactionResponse) Reset() {
	*x = BroadcastTransactionResponse{}
	mi := &file_src_proto_network_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastTransactionResponse) ProtoMessage() {}

func (x *BroadcastTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastTransactionResponse.ProtoReflect.Descriptor instead.
func (*BroadcastTransactionResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{22}
}

func (x *BroadcastTransactionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BroadcastTransactionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BroadcastTransactionResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

// GetLatestCheckpointRequest requests the latest checkpoint
type GetLatestCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestCheckpointRequest) Reset() {
	*x = GetLatestCheckpointRequest{}
	mi := &file_src_proto_network_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCheckpointRequest) ProtoMessage() {}

func (x *GetLatestCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetLatestCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{23}
}

func (x *GetLatestCheckpointRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// GetLatestCheckpointResponse returns the latest checkpoint info
type GetLatestCheckpointResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HasCheckpoint  bool                   `protobuf:"varint,1,opt,name=has_checkpoint,json=hasCheckpoint,proto3" json:"has_checkpoint,omitempty"`
	BlockNumber    uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`         // Block number where checkpoint was created
	StateBlock     uint64                 `protobuf:"varint,3,opt,name=state_block,json=stateBlock,proto3" json:"state_block,omitempty"`            // Block number of the state in checkpoint
	Cid            string                 `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`                                             // IPFS CID of checkpoint
	CheckpointHash []byte                 `protobuf:"bytes,5,opt,name=checkpoint_hash,json=checkpointHash,proto3" json:"checkpoint_hash,omitempty"` // Hash of checkpoint for validation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLatestCheckpointResponse) Reset() {
	*x = GetLatestCheckpointResponse{}
	mi := &file_src_proto_network_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestCheckpointResponse) ProtoMessage() {}

func (x *GetLatestCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_network_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestCheckpointResponse.ProtoReflect.Descriptor instead.
func (*GetLatestCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_src_proto_network_proto_rawDescGZIP(), []int{24}
}

func (x *GetLatestCheckpointResponse) GetHasCheckpoint() bool {
	if x != nil {
		return x.HasCheckpoint
	}
	return false
}

func (x *GetLatestCheckpointResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetLatestCheckpointResponse) GetStateBlock() uint64 {
	if x != nil {
		return x.StateBlock
	}
	return 0
}

func (x *GetLatestCheckpointResponse) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *GetLatestCheckpointResponse) GetCheckpointHash() []byte {
	if x != nil {
		return x.CheckpointHash
	}
	return nil
}

var File_src_proto_network_proto protoreflect.FileDescriptor

const file_src_proto_network_proto_rawDesc = "" +
	"\n" +
	"\x17src/proto/network.proto\x12\anetwork\"f\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12'\n" +
	"\x0fconnected_since\x18\x03 \x01(\x03R\x0econnectedSince\"\x93\x01\n" +
	"\x10HandshakeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\"\xbb\x01\n" +
	"\x11HandshakeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0enonce_response\x18\x06 \x01(\fR\rnonceResponse\"D\n" +
	"\x0fGetPeersRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tmax_peers\x18\x02 \x01(\x05R\bmaxPeers\";\n" +
	"\x10GetPeersResponse\x12'\n" +
	"\x05peers\x18\x01 \x03(\v2\x11.network.PeerInfoR\x05peers\"A\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"W\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"A\n" +
	"\x11DisconnectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"8\n" +
	"\x12DisconnectResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"\x9b\x01\n" +
	"\x14AuthenticatedRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\x80\x01\n" +
	"\x15AuthenticatedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xe6\x02\n" +
	"\x05Block\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12#\n" +
	"\rprevious_hash\x18\x02 \x01(\fR\fpreviousHash\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12#\n" +
	"\rminer_address\x18\x04 \x01(\fR\fminerAddress\x12\x17\n" +
	"\atx_root\x18\x05 \x01(\fR\x06txRoot\x12\x1d\n" +
	"\n" +
	"state_root\x18\x06 \x01(\fR\tstateRoot\x12%\n" +
	"\x0echeckpoint_cid\x18\a \x01(\tR\rcheckpointCid\x12'\n" +
	"\x0fcheckpoint_hash\x18\b \x01(\fR\x0echeckpointHash\x128\n" +
	"\ftransactions\x18\t \x03(\v2\x14.network.TransactionR\ftransactions\x12\x1b\n" +
	"\tminer_sig\x18\n" +
	" \x01(\fR\bminerSig\"\xb2\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x17\n" +
	"\atx_type\x18\x02 \x01(\rR\x06txType\x12\x1c\n" +
	"\tvalidator\x18\x03 \x01(\fR\tvalidator\x12\x12\n" +
	"\x04from\x18\x04 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\fR\x02to\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\x12\x14\n" +
	"\x05nonce\x18\a \x01(\fR\x05nonce\x12\x1f\n" +
	"\vblock_limit\x18\b \x01(\x04R\n" +
	"blockLimit\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x12\x19\n" +
	"\buser_sig\x18\n" +
	" \x01(\fR\auserSig\x12\x1f\n" +
	"\vsequence_id\x18\v \x01(\x04R\n" +
	"sequenceId\x12<\n" +
	"\bread_set\x18\f \x03(\v2!.network.Transaction.ReadSetEntryR\areadSet\x12?\n" +
	"\twrite_set\x18\r \x03(\v2\".network.Transaction.WriteSetEntryR\bwriteSet\x12#\n" +
	"\rvalidator_sig\x18\x0e \x01(\fR\fvalidatorSig\x1a:\n" +
	"\fReadSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rWriteSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"S\n" +
	"\x15BroadcastBlockRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12$\n" +
	"\x05block\x18\x02 \x01(\v2\x0e.network.BlockR\x05block\"L\n" +
	"\x16BroadcastBlockResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"S\n" +
	"\x0fGetBlockRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\fR\x04hash\"N\n" +
	"\x10GetBlockResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12$\n" +
	"\x05block\x18\x02 \x01(\v2\x0e.network.BlockR\x05block\"|\n" +
	"\x10GetBlocksRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\vfrom_number\x18\x02 \x01(\x04R\n" +
	"fromNumber\x12\x1b\n" +
	"\tto_number\x18\x03 \x01(\x04R\btoNumber\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\";\n" +
	"\x11GetBlocksResponse\x12&\n" +
	"\x06blocks\x18\x01 \x03(\v2\x0e.network.BlockR\x06blocks\"-\n" +
	"\x15GetLatestBlockRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"D\n" +
	"\x16GetLatestBlockResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"k\n" +
	"\x1bBroadcastTransactionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x126\n" +
	"\vtransaction\x18\x02 \x01(\v2\x14.network.TransactionR\vtransaction\"g\n" +
	"\x1cBroadcastTransactionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\"2\n" +
	"\x1aGetLatestCheckpointRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xc3\x01\n" +
	"\x1bGetLatestCheckpointResponse\x12%\n" +
	"\x0ehas_checkpoint\x18\x01 \x01(\bR\rhasCheckpoint\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12\x1f\n" +
	"\vstate_block\x18\x03 \x01(\x04R\n" +
	"stateBlock\x12\x10\n" +
	"\x03cid\x18\x04 \x01(\tR\x03cid\x12'\n" +
	"\x0fcheckpoint_hash\x18\x05 \x01(\fR\x0echeckpointHash2\xca\x06\n" +
	"\vNodeService\x12B\n" +
	"\tHandshake\x12\x19.network.HandshakeRequest\x1a\x1a.network.HandshakeResponse\x12?\n" +
	"\bGetPeers\x12\x18.network.GetPeersRequest\x1a\x19.network.GetPeersResponse\x123\n" +
	"\x04Ping\x12\x14.network.PingRequest\x1a\x15.network.PingResponse\x12E\n" +
	"\n" +
	"Disconnect\x12\x1a.network.DisconnectRequest\x1a\x1b.network.DisconnectResponse\x12H\n" +
	"\aRequest\x12\x1d.network.AuthenticatedRequest\x1a\x1e.network.AuthenticatedResponse\x12Q\n" +
	"\x0eBroadcastBlock\x12\x1e.network.BroadcastBlockRequest\x1a\x1f.network.BroadcastBlockResponse\x12?\n" +
	"\bGetBlock\x12\x18.network.GetBlockRequest\x1a\x19.network.GetBlockResponse\x12B\n" +
	"\tGetBlocks\x12\x19.network.GetBlocksRequest\x1a\x1a.network.GetBlocksResponse\x12Q\n" +
	"\x0eGetLatestBlock\x12\x1e.network.GetLatestBlockRequest\x1a\x1f.network.GetLatestBlockResponse\x12c\n" +
	"\x14BroadcastTransaction\x12$.network.BroadcastTransactionRequest\x1a%.network.BroadcastTransactionResponse\x12`\n" +
	"\x13GetLatestCheckpoint\x12#.network.GetLatestCheckpointRequest\x1a$.network.GetLatestCheckpointResponseB*Z(github.com/bywise/go-bywise/src/proto/pbb\x06proto3"

var (
	file_src_proto_network_proto_rawDescOnce sync.Once
	file_src_proto_network_proto_rawDescData []byte
)

func file_src_proto_network_proto_rawDescGZIP() []byte {
	file_src_proto_network_proto_rawDescOnce.Do(func() {
		file_src_proto_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_network_proto_rawDesc), len(file_src_proto_network_proto_rawDesc)))
	})
	return file_src_proto_network_proto_rawDescData
}

var file_src_proto_network_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_src_proto_network_proto_goTypes = []any{
	(*PeerInfo)(nil),                     // 0: network.PeerInfo
	(*HandshakeRequest)(nil),             // 1: network.HandshakeRequest
	(*HandshakeResponse)(nil),            // 2: network.HandshakeResponse
	(*GetPeersRequest)(nil),              // 3: network.GetPeersRequest
	(*GetPeersResponse)(nil),             // 4: network.GetPeersResponse
	(*PingRequest)(nil),                  // 5: network.PingRequest
	(*PingResponse)(nil),                 // 6: network.PingResponse
	(*DisconnectRequest)(nil),            // 7: network.DisconnectRequest
	(*DisconnectResponse)(nil),           // 8: network.DisconnectResponse
	(*AuthenticatedRequest)(nil),         // 9: network.AuthenticatedRequest
	(*AuthenticatedResponse)(nil),        // 10: network.AuthenticatedResponse
	(*Block)(nil),                        // 11: network.Block
	(*Transaction)(nil),                  // 12: network.Transaction
	(*BroadcastBlockRequest)(nil),        // 13: network.BroadcastBlockRequest
	(*BroadcastBlockResponse)(nil),       // 14: network.BroadcastBlockResponse
	(*GetBlockRequest)(nil),              // 15: network.GetBlockRequest
	(*GetBlockResponse)(nil),             // 16: network.GetBlockResponse
	(*GetBlocksRequest)(nil),             // 17: network.GetBlocksRequest
	(*GetBlocksResponse)(nil),            // 18: network.GetBlocksResponse
	(*GetLatestBlockRequest)(nil),        // 19: network.GetLatestBlockRequest
	(*GetLatestBlockResponse)(nil),       // 20: network.GetLatestBlockResponse
	(*BroadcastTransactionRequest)(nil),  // 21: network.BroadcastTransactionRequest
	(*BroadcastTransactionResponse)(nil), // 22: network.BroadcastTransactionResponse
	(*GetLatestCheckpointRequest)(nil),   // 23: network.GetLatestCheckpointRequest
	(*GetLatestCheckpointResponse)(nil),  // 24: network.GetLatestCheckpointResponse
	nil,                                  // 25: network.Transaction.ReadSetEntry
	nil,                                  // 26: network.Transaction.WriteSetEntry
}
var file_src_proto_network_proto_depIdxs = []int32{
	0,  // 0: network.GetPeersResponse.peers:type_name -> network.PeerInfo
	12, // 1: network.Block.transactions:type_name -> network.Transaction
	25, // 2: network.Transaction.read_set:type_name -> network.Transaction.ReadSetEntry
	26, // 3: network.Transaction.write_set:type_name -> network.Transaction.WriteSetEntry
	11, // 4: network.BroadcastBlockRequest.block:type_name -> network.Block
	11, // 5: network.GetBlockResponse.block:type_name -> network.Block
	11, // 6: network.GetBlocksResponse.blocks:type_name -> network.Block
	12, // 7: network.BroadcastTransactionRequest.transaction:type_name -> network.Transaction
	1,  // 8: network.NodeService.Handshake:input_type -> network.HandshakeRequest
	3,  // 9: network.NodeService.GetPeers:input_type -> network.GetPeersRequest
	5,  // 10: network.NodeService.Ping:input_type -> network.PingRequest
	7,  // 11: network.NodeService.Disconnect:input_type -> network.DisconnectRequest
	9,  // 12: network.NodeService.Request:input_type -> network.AuthenticatedRequest
	13, // 13: network.NodeService.BroadcastBlock:input_type -> network.BroadcastBlockRequest
	15, // 14: network.NodeService.GetBlock:input_type -> network.GetBlockRequest
	17, // 15: network.NodeService.GetBlocks:input_type -> network.GetBlocksRequest
	19, // 16: network.NodeService.GetLatestBlock:input_type -> network.GetLatestBlockRequest
	21, // 17: network.NodeService.BroadcastTransaction:input_type -> network.BroadcastTransactionRequest
	23, // 18: network.NodeService.GetLatestCheckpoint:input_type -> network.GetLatestCheckpointRequest
	2,  // 19: network.NodeService.Handshake:output_type -> network.HandshakeResponse
	4,  // 20: network.NodeService.GetPeers:output_type -> network.GetPeersResponse
	6,  // 21: network.NodeService.Ping:output_type -> network.PingResponse
	8,  // 22: network.NodeService.Disconnect:output_type -> network.DisconnectResponse
	10, // 23: network.NodeService.Request:output_type -> network.AuthenticatedResponse
	14, // 24: network.NodeService.BroadcastBlock:output_type -> network.BroadcastBlockResponse
	16, // 25: network.NodeService.GetBlock:output_type -> network.GetBlockResponse
	18, // 26: network.NodeService.GetBlocks:output_type -> network.GetBlocksResponse
	20, // 27: network.NodeService.GetLatestBlock:output_type -> network.GetLatestBlockResponse
	22, // 28: network.NodeService.BroadcastTransaction:output_type -> network.BroadcastTransactionResponse
	24, // 29: network.NodeService.GetLatestCheckpoint:output_type -> network.GetLatestCheckpointResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_src_proto_network_proto_init() }
func file_src_proto_network_proto_init() {
	if File_src_proto_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_network_proto_rawDesc), len(file_src_proto_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_network_proto_goTypes,
		DependencyIndexes: file_src_proto_network_proto_depIdxs,
		MessageInfos:      file_src_proto_network_proto_msgTypes,
	}.Build()
	File_src_proto_network_proto = out.File
	file_src_proto_network_proto_goTypes = nil
	file_src_proto_network_proto_depIdxs = nil
}
